name: Test and Lint development code

on:
  push:
    branches-ignore:
      - production
    paths-ignore:
      - '**.md'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js 14
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install dependencies
        run: |
          npm ci

      - name: Lint using ESlint
        run: |
          npm run lint

      - name: Test with Jest & Supertest
        run: |
          npm run test
